
# This name can be anything but must be unique for each patient

RIT005:
  FAfiles:
    -
      File:
      FA:
    -
      File:
      FA:
    -
      File:
      FA:

  Settings:
    Output_file: /