
# Config file for running T10 modelling
# Note that yaml files can be written manually or automatically
#

# This name can be anything but must be unique for each patient
EG1:

  Folder:   /mnt/ibme/Ben-Thais-Jola_examples/

  Files:
      File: Lungs_vfa3d.nii
      FA:
          - 1.0
          - 1.2
          - 1.4
          - 1.6
          - 1.8
          - 2.0
          - 2.2
          - 2.4
          - 2.7
          - 3.1
          - 3.7
          - 4.4
          - 5.2
          - 6.1
          - 7.0
          - 8.0
              

  Settings:
    TR:           0.0035  # seconds (s)
    Out_file_path: /mnt/ibme/Ben-Thais-Jola_examples/T10.nii
