### Example config file for PK modelling 

#  Model descriptions:
#  Model 1: Orton with offset (Clinical) - Recommended model for clinical
#  Model 2: Orton without offset (Clinical)
#  Model 3: Weinmann with offset (Pre-clinical) - Recommended model for preclinical
#  Model 4: Weinmann with offset and vp (Pre-clinical)

OutputFolder: out
#Debug: True

Processing:
  - PkModelling:
      model_choice: 1
      flip_angle: 30    # degrees
      TR:         5.0   # ms
      TE:         2.2   # ms
      T:          0.5    # temporal resolution (s)
      R1:         3.7
      R2:         4.8
      v1thresh:   99.8
      # Approximate injection time (s) - e.g. number_of_slices*temporal resolution
      InjT:       60
      # Smoothing of the PK maps
      Smoothing:  1 # TODO

SaveOverlays:
  kep:
  Ktrans:
  model_curves:

Cases:
    QIBA1:
        Folder:   c:\Users\ctsu0221\build\data\testdata\qiba\
        Volume:   qiba.nii
        Overlays:
          T10: qiba_t1_new.nii
        Rois:
          mask: qiba_mask_onevox.nii


