# Lists the configuration for running DCE-MRI from the command line
# (c) Benjamin Irving (2016)

EG1:

  Name:

  Files:
      DCE:       /data1/Results/2_pk_RIT_motioncor/RIT005/DCE.nii
      T10:        /data1/Results/2_pk_RIT_motioncor/RIT005/T10.nii
      ROI:       /data1/Results/2_pk_RIT_motioncor/RIT005/seg.nii

  Output_folder:  /data1/Results/2_pk_RIT_motioncor/RIT005/test/ # TODO

  Param:
      flip_angle: 12    # degrees
      TR:         4.5   # ms
      TE:         2.2   # ms
      T:          17    # temporal resolution (s)
      R1:         3.7
      R2:         4.8
      v1thresh:   99.8
      # Approximate injection time (s) - e.g. number_of_slices*temporal resolution
      InjT:       60
      # Smoothing of the PK maps
      Smoothing:  1 # TODO

  Configuration:
      model_choice: 1

#  Model descriptions:
#  Model 1: Orton with offset (Clinical) - Recommended model for clinical
#  Model 2: Orton without offset (Clinical)
#  Model 3: Weinmann with offset (Pre-clinical) - Recommended model for preclinical
#  Model 4: Weinmann with offset and vp (Pre-clinical)


