### Illustration of proposed YAML-based batch file format

# Global output folder - each case is output in a separate subfolder
OutputFolder: output

# Setting to True will create LOTS of debugging output
Debug: False

# Defines the processing to be done on each case
# This is given as a list so the order of tasks is preserved
Processing:

  # Load data - file names are relative to case folder. Can define data to be loaded
  # globally or individually per case
  - Load: 

  # Run some processing steps - in this case motion correction followed by model fitting
  - Moco:
      method: flirt
      replace-vol: True
      cost: normcorr

  - Fabber:
      method: vb
      max-iterations: 30
      model:  poly
      degree: 2 
      save-mean:

  # Output data
  # Note that the output folder is used to form the filename
  - Save:
      mean_c0:
      mean_c1:
      mean_c2:
      mask: seg.nii

# List of cases to apply the processing to
Cases:
    Pipeline:
        # Note that the folder is used to form input filenames
        InputFolder:   data_autogen

        # Data to load for this case
        Load:
          data:
            testdata_4d.nii.gz:
          rois:
            testdata_mask.nii.gz: mask
          
        # Can override processing defaults here
        Moco:
          refvol: 10 


