# Example config file for replacing ROI region with the mean data value

OutputFolder: test/examples_output
Debug: False

Processing:
  - Load:
        data:
            testdata_3d.nii.gz:
        rois:
            testdata_mask.nii.gz: mask

  - MeanValues:
        data: testdata_3d
        roi: mask
        output-name: testdata_mean

  - Save:
      testdata_mean:

Cases:
    EG14:
        Folder:   test/data_autogen


