### Example config file for PK modelling 

#  Model descriptions:
#  Model 1: Orton with offset (Clinical) - Recommended model for clinical
#  Model 2: Orton without offset (Clinical)
#  Model 3: Weinmann with offset (Pre-clinical) - Recommended model for preclinical
#  Model 4: Weinmann with offset and vp (Pre-clinical)

OutputFolder: out
Debug: False

Processing:
  - Load:
  
  - PkModelling:
      model:      1      # Model (see above)
      fa:         30     # degrees
      tr:         3.5    # ms
      te:         1.6    # ms
      dt:         0.5    # temporal resolution (s)
      r1:         3.7    # T1 Relaxivity of contrast agent
      r2:         4.8    # T2 Relaxivity of contrast agent
      ve-thresh:  99.8   # Ktrans/kep percentile threshold
      tinj:       60     # Approximate injection time (s) - e.g. number_of_slices*temporal resolution
      #smoothing:  1      # Smoothing of the PK maps - TODO

  - Save:
      kep:
      ktrans:
      ve:
      vp:
      offset:
      model_curves:

Cases:
    QIBA1:
        Folder:   c:\Users\ctsu0221\build\data\testdata\qiba\
        Load:
          data:
            qiba_67tpts.nii:
            qiba_t10.nii: T10
          rois:
            qiba_mask.nii: mask


