### Example config file for PK modelling 

#  Model descriptions:
#  Model 1: Orton with offset (Clinical) - Recommended model for clinical
#  Model 2: Orton without offset (Clinical)
#  Model 3: Weinmann with offset (Pre-clinical) - Recommended model for preclinical
#  Model 4: Weinmann with offset and vp (Pre-clinical)

OutputFolder: out
#Debug: True

Processing:
  - PkModelling:
      model:      1
      fa:         30     # degrees
      tr:         5.0    # ms
      te:         2.2    # ms
      dt:         0.5    # temporal resolution (s)
      r1:         3.7    # T1 Relaxivity of contrast agent
      r2:         4.8    # T2 Relaxivity of contrast agent
      ve-thresh:   99.8   # Ktrans/kep percentile threshold
      tinj:       60     # Approximate injection time (s) - e.g. number_of_slices*temporal resolution
      #smoothing:  1      # Smoothing of the PK maps - TODO

SaveOverlays:
  kep:
  ktrans:
  ve:
  vp:
  offset:
  Model curves:

Cases:
    QIBA1:
        Folder:   c:\Users\ctsu0221\build\data\testdata\qiba\
        Volume:   qiba_67tpts.nii
        Overlays:
          T10: qiba_t10.nii
        Rois:
          mask: qiba_mask.nii


