### Example config file for T10 modelling without B0 correction

OutputFolder: out
#Debug: True

Processing:
  - T10:
      tr: 0.0035 # seconds
      clamp:
        min: 0
        max: 5

SaveOverlays:
    T10:

Cases:
    RIT005:
        Folder:   c:\Users\ctsu0221\build\data\Martin_test_data\RIT005_PRE
        Volume:   dceMRI.nii
        T10:
          vfa:
            fa3_aligned.nii : 3
            fa9_aligned.nii : 9
            fa15_aligned.nii : 15
